Repository mapshare/mobile-app-frontend, pull requests merged in 2019-10, with the labels that each got.

#4 [MAF-2] redux store setup
  .env
  App.js
  android/gradle.properties
  package-lock.json
  package.json
  src/actions/logInActions.js
  src/actions/registerActions.js
  src/data/key.js
  src/reducers/logInReducer.js
  src/reducers/registerReducer.js
  src/reducers/rootReducer.js
  src/reduxStore/configureStore.js
  src/screens/Forms/Login/LoginForm.js
  src/screens/Forms/SignUp/SignUpForm.js
Labels: enhancement

#5 A2: Merge All Changes to Develop
  Readme.txt
  android/app/build.gradle
  android/app/src/main/assets/index.android.bundle
  android/app/src/main/java/com/pinit/MainApplication.java
  android/app/src/main/res/drawable-hdpi/node_modules_reactnavigationstack_dist_views_assets_backicon.png
  android/app/src/main/res/drawable-mdpi/node_modules_reactnativerouterflux_images_back_chevron.png
  android/app/src/main/res/drawable-mdpi/node_modules_reactnativerouterflux_images_menu_burger.png
  android/app/src/main/res/drawable-mdpi/node_modules_reactnavigationstack_dist_views_assets_backicon.png
  android/app/src/main/res/drawable-mdpi/node_modules_reactnavigationstack_dist_views_assets_backiconmask.png
  android/app/src/main/res/drawable-mdpi/src_assests_images_logo.png
  android/app/src/main/res/drawable-xhdpi/node_modules_reactnavigationstack_dist_views_assets_backicon.png
  android/app/src/main/res/drawable-xxhdpi/node_modules_reactnavigationstack_dist_views_assets_backicon.png
  android/app/src/main/res/drawable-xxxhdpi/node_modules_reactnavigationstack_dist_views_assets_backicon.png
  android/app/src/main/res/raw/app.json
  android/build.gradle
  android/gradle.properties
  android/settings.gradle
  package-lock.json
  package.json
  src/navigation/router.js
  src/screens/Events/Event.js
  src/screens/Events/Stylesheet.js
  src/screens/Forms/Login/LoginForm.js
  src/screens/Forms/SignUp/SignUpForm.js
  src/screens/Forms/Stylesheet.js
  src/screens/GroupChat/GroupChat.js
  src/screens/GroupChat/Stylesheet.js
  src/screens/Home/Stylesheet.js
  src/screens/Home/home.js
  src/screens/Login/Login.js
  src/screens/Login/Stylesheet.js
  src/screens/Map/Map.js
  src/screens/Map/Stylesheet.js
  src/screens/Profile/Profile.js
  src/screens/Profile/Stylesheet.js
  src/screens/SignUp/SignUp.js
  src/screens/SignUp/Stylesheet.js
Labels: enhancement

#6 redux setup for signup and login
  src/screens/Forms/Login/LoginForm.js
  src/screens/Forms/SignUp/SignUpForm.js
Labels: bug, enhancement

#7 fix loginForm redux setup
  src/screens/Forms/Login/LoginForm.js
  src/screens/Forms/SignUp/SignUpForm.js
Labels: bug, enhancement

#8 Replace config with dotenv. Setup login and signup
  .env
  babel.config.js
  package-lock.json
  package.json
  src/actions/logInActions.js
  src/actions/registerActions.js
  src/data/key.js
  src/reducers/logInReducer.js
  src/screens/Forms/Login/LoginForm.js
  src/screens/Forms/SignUp/SignUpForm.js
Labels: enhancement

#10 Fixed Dependencies Issue
  App.js
  android/app/build.gradle
  android/build.gradle
  android/settings.gradle
  package-lock.json
  package.json
  src/screens/Map/Map.js
Labels: bug

#11 Added Login and SignUp form input validation
  package-lock.json
  package.json
  src/actions/logInActions.js
  src/actions/registerActions.js
  src/data/key.js
  src/reducers/logInReducer.js
  src/reducers/registerReducer.js
  src/screens/Forms/Login/LoginForm.js
  src/screens/Forms/SignUp/SignUpForm.js
  src/screens/Forms/validate/validation.js
  src/screens/Forms/validate/validation_wrapper.js
Labels: enhancement

#14 Ready for review - Setting up Group Chat
  .env
  package-lock.json
  package.json
  src/actions/groupActions.js
  src/actions/groupChatRoomAction.js
  src/data/key.js
  src/navigation/router.js
  src/reducers/groupChatRoomReducer.js
  src/reducers/groupEventReducer.js
  src/reducers/groupReducer.js
  src/reducers/rootReducer.js
  src/screens/Forms/AddChatRoom/AddChatRoomForm.js
  src/screens/Forms/AddGroup/AddGroupFrom.js
  src/screens/Forms/SearchChatRoom/SearchChatRoom.js
  src/screens/Forms/SearchGroup/SearchGroupForm.js
  src/screens/GroupChat/GroupChat.js
  src/screens/GroupChat/Stylesheet.js
  src/screens/Home/home.js
  src/screens/ManageGroup/AddGroup/AddGroup.js
  src/screens/ManageGroup/AddGroup/Stylesheet.js
  src/screens/ManageGroup/ManageGroup.js
  src/screens/ManageGroup/ManageGroupJoinRequests/ManageGroupJoinRequests.js
  src/screens/ManageGroup/ManageGroupJoinRequests/Stylesheet.js
  src/screens/ManageGroup/SelectGroup/SelectGroup.js
  src/screens/ManageGroup/SelectGroup/Stylesheet.js
  src/screens/ManageGroup/Stylesheet.js
  src/screens/ManageGroupChat/AddChatRoom/AddChatRoom.js
  src/screens/ManageGroupChat/AddChatRoom/Stylesheet.js
  src/screens/ManageGroupChat/GroupChat/GroupChat.js
  src/screens/ManageGroupChat/GroupChat/Stylesheet.js
  src/screens/ManageGroupChat/ManageGroupChat.js
  src/screens/ManageGroupChat/SelectChatRoom/SelectChatRoom.js
  src/screens/ManageGroupChat/SelectChatRoom/Stylesheet.js
  src/screens/ManageGroupChat/Stylesheet.js
Labels: enhancement

#13 Maf 9 mapbox
  .env
  .prettierrc.js
  package-lock.json
  package.json
  src/actions/groupMarkAction.js
  src/actions/modalWindowAction.js
  src/data/key.js
  src/navigation/router.js
  src/reducers/groupEventReducer.js
  src/reducers/groupMarkReducer.js
  src/reducers/modalWindowReducer.js
  src/reducers/rootReducer.js
  src/screens/Forms/Login/LoginForm.js
  src/screens/Forms/SignUp/SignUpForm.js
  src/screens/GroupChat/GroupChat.js
  src/screens/Map/Map.js
  src/screens/Map/Stylesheet.js
  src/screens/ModalWindow/ModalWindow.js
  src/screens/ModalWindow/Stylesheet.js
  src/util/sharedStyles.js
Labels: enhancement
