Repository mapshare/mobile-app-frontend, pull requests merged in 2019-11, with the labels that each got.

#24 Added leave and delete group. And bug fixes
  src/actions/groupActions.js
  src/screens/Forms/AddChatRoom/AddChatRoomForm.js
  src/screens/Forms/AddGroup/AddGroupFrom.js
  src/screens/Forms/Login/LoginForm.js
  src/screens/Home/home.js
  src/screens/ManageGroup/ManageGroup.js
  src/screens/ManageGroup/ManageGroupJoinRequests/ManageGroupJoinRequests.js
  src/screens/ManageGroup/SelectGroup/SelectGroup.js
  src/screens/ManageGroupChat/ManageGroupChat.js
  src/screens/ManageGroupChat/SelectChatRoom/SelectChatRoom.js
Labels: enhancement

#27 Added Group Menu
  src/actions/AddGroupFormAction.js
  src/actions/GroupMenuAction.js
  src/actions/SearchGroupFormAction.js
  src/actions/groupActions.js
  src/data/key.js
  src/reducers/AddGroupFromReducer.js
  src/reducers/GroupMenuReducer.js
  src/reducers/SearchGroupFromReducer.js
  src/reducers/groupReducer.js
  src/reducers/rootReducer.js
  src/screens/Forms/AddGroup/AddGroupFrom.js
  src/screens/Forms/SearchGroup/SearchGroupForm.js
  src/screens/Forms/Stylesheet.js
  src/screens/Home/GroupMenu/GroupMenu.js
  src/screens/Home/GroupMenu/Menus/AddGroup.js
  src/screens/Home/GroupMenu/Menus/EditGroup.js
  src/screens/Home/GroupMenu/Menus/JoinGroupRequest.js
  src/screens/Home/GroupMenu/Menus/MyGroups.js
  src/screens/Home/GroupMenu/Menus/SearchGroup.js
  src/screens/Home/GroupMenu/Stylesheet.js
  src/screens/Home/Home.js
Labels: enhancement

#28 AddMark redux form
  package-lock.json
  package.json
  src/actions/groupMarkAction.js
  src/data/key.js
  src/reducers/groupMarkReducer.js
  src/reducers/rootReducer.js
  src/screens/AddMark/AddMark.js
  src/screens/AddMark/Stylesheet.js
  src/screens/Forms/AddMark/AddMarkForm.js
  src/screens/Forms/AddMark/Stylesheet.js
  src/screens/Forms/Login/LoginForm.js
  src/screens/Forms/RenderField/RenderField.js
  src/screens/Forms/RenderField/Stylesheet.js
  src/screens/Forms/validate/validation.js
  src/screens/Map/Map.js
  src/screens/Map/Stylesheet.js
  src/screens/ModalWindow/ModalWindow.js
  src/screens/ModalWindow/Stylesheet.js
Labels: enhancement

#34 Add Group Feed And Bug Fixes
  package-lock.json
  package.json
  src/actions/GroupMenuAction.js
  src/actions/addPostActions.js
  src/actions/groupActions.js
  src/actions/groupChatRoomAction.js
  src/actions/groupFeedAction.js
  src/actions/logInActions.js
  src/data/key.js
  src/navigation/Router/router.js
  src/reducers/GroupMenuReducer.js
  src/reducers/addPostReducer.js
  src/reducers/groupChatRoomReducer.js
  src/reducers/groupFeedReducer.js
  src/reducers/groupReducer.js
  src/reducers/rootReducer.js
  src/screens/Forms/CreatePost/CreatePost.js
  src/screens/Forms/SearchGroup/SearchGroupForm.js
  src/screens/Forms/Stylesheet.js
  src/screens/Groups/GroupChat/GroupChat.js
  src/screens/Groups/GroupFeed/CreatePostButton.js
  src/screens/Groups/GroupFeed/GroupFeed.js
  src/screens/Groups/GroupFeed/Stylesheet.js
  src/screens/Home/GroupMenu/Menus/EditGroup.js
  src/screens/Home/GroupMenu/Menus/EditGroupMember.js
  src/screens/Home/GroupMenu/Menus/GroupMembersList.js
  src/screens/Home/GroupMenu/Menus/JoinGroupRequest.js
  src/screens/Home/GroupMenu/Menus/MyGroups.js
  src/screens/Home/GroupMenu/Menus/SearchGroup.js
  src/screens/Home/GroupMenu/Stylesheet.js
  src/screens/Home/Home.js
  src/screens/Home/Stylesheet.js
  src/screens/InitialGroupMenu/Menus/MyGroups.js
  src/screens/InitialGroupMenu/Menus/SearchGroup.js
  src/screens/Loading/Loading.js
Labels: enhancement

#33 Wz location
  .env
  .gitignore
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/assets/index.android - Copy.bundle
  android/app/src/main/assets/index.android.bundle
  android/app/src/main/java/com/pinit/MainApplication.java
  android/app/src/main/java/com/pinit/SplashActivity.java
  android/app/src/main/res/drawable-mdpi/node_modules_reactnativegoogleplacesautocomplete_images_powered_by_google_on_white.png
  android/app/src/main/res/drawable-xhdpi/node_modules_reactnativegoogleplacesautocomplete_images_powered_by_google_on_white.png
  android/app/src/main/res/drawable-xxhdpi/node_modules_reactnativegoogleplacesautocomplete_images_powered_by_google_on_white.png
  android/app/src/main/res/drawable/background_splash.xml
  android/app/src/main/res/layout/launch_screen.xml
  android/app/src/main/res/mipmap-mdpi/logo.png
  android/app/src/main/res/mipmap-xhdpi/logo.png
  android/app/src/main/res/mipmap-xxhdpi/logo.png
  android/app/src/main/res/mipmap-xxxhdpi/logo.png
  android/app/src/main/res/values/color.xml
  android/app/src/main/res/values/styles.xml
  package-lock.json
  package.json
  src/actions/logInActions.js
  src/actions/registerActions.js
  src/screens/Login/Login.js
  src/screens/Map/Map.js
  src/screens/Map/Search.js
  src/screens/Map/Stylesheet.js
Labels: bug, enhancement

#39 Wz mapfix
  android/app/src/main/assets/index.android.bundle
  src/screens/Login/Login.js
  src/screens/Map/Map.js
  src/screens/SignUp/SignUp.js
Labels: bug

#40 Bug fixes
  src/actions/groupActions.js
  src/screens/Home/GroupMenu/Menus/EditGroup.js
  src/screens/Home/GroupMenu/Menus/GroupMembersList.js
  src/screens/Home/GroupMenu/Menus/MyGroups.js
  src/screens/Home/Home.js
  src/screens/InitialGroupMenu/Menus/MyGroups.js
  src/screens/InitialGroupMenu/Menus/SearchGroup.js
  src/screens/InitialGroupMenu/Stylesheet.js
  src/screens/Profile/Profile.js
  src/screens/Profile/Stylesheet.js
Labels: bug

#41 MAF 29 location detail window
  App.js
  package-lock.json
  package.json
  src/actions/SearchGroupFormAction.js
  src/actions/groupActions.js
  src/actions/groupMarkAction.js
  src/actions/logInActions.js
  src/actions/modalWindowAction.js
  src/actions/registerActions.js
  src/data/key.js
  src/reducers/SearchGroupFromReducer.js
  src/reducers/groupMarkReducer.js
  src/reducers/groupReducer.js
  src/reducers/modalWindowReducer.js
  src/screens/Forms/AddMark/AddMarkForm.js
  src/screens/Forms/CreateGroup/GroupForm.js
  src/screens/Forms/Login/LoginForm.js
  src/screens/Forms/RenderField/RenderField.js
  src/screens/Home/Home.js
  src/screens/LocationDetailWindow/LocationDetailWindow.js
  src/screens/LocationDetailWindow/Stylesheet.js
  src/screens/Map/Map.js
  src/screens/Marks/Marks.js
  src/screens/Marks/Stylesheet.js
  src/screens/ModalWindow/ModalWindow.js
  src/screens/ModalWindow/Stylesheet.js
Labels: enhancement

#42 Fix add mark form
  src/actions/groupMarkAction.js
  src/screens/Forms/AddMark/AddMarkForm.js
  src/screens/Forms/AddMark/Stylesheet.js
  src/screens/Forms/RenderField/RenderField.js
  src/screens/Forms/RenderField/Stylesheet.js
  src/screens/Forms/validate/validation.js
Labels: enhancement

#45 Small fixes validation style
  src/actions/groupMarkAction.js
  src/data/key.js
  src/navigation/Router/router.js
  src/reducers/groupMarkReducer.js
  src/screens/Forms/AddMark/AddMarkForm.js
  src/screens/Forms/EditPost/EditPost.js
  src/screens/Forms/RenderField/RenderField.js
  src/screens/Forms/validate/validation.js
  src/screens/Forms/validate/validation_wrapper.js
  src/screens/Home/Home.js
  src/screens/LocationDetailWindow/LocationDetailWindow.js
  src/screens/Map/Map.js
  src/screens/Marks/Marks.js
  src/screens/ModalWindow/ModalWindow.js
  src/screens/ModalWindow/Stylesheet.js
Labels: bug, enhancement

#46 Optimizations and Additions
  src/actions/groupActions.js
  src/data/key.js
  src/navigation/Router/router.js
  src/reducers/groupReducer.js
  src/screens/Forms/AddGroup/AddGroupFrom.js
  src/screens/Forms/ChangeGroupDescription/ChangeGroupDescriptionForm.js
  src/screens/Forms/ChangeGroupName/ChangeGroupNameForm.js
  src/screens/Forms/CreatePost/CreatePost.js
  src/screens/Forms/EditPost/EditPost.js
  src/screens/Forms/SearchGroup/SearchGroupForm.js
  src/screens/Forms/Stylesheet.js
  src/screens/Forms/validate/validation.js
  src/screens/Groups/GroupChat/GroupChat.js
  src/screens/Groups/GroupFeed/CreatePostButton.js
  src/screens/Groups/GroupFeed/GroupFeed.js
  src/screens/Groups/GroupFeed/Stylesheet.js
  src/screens/Home/GroupMenu/GroupMenu.js
  src/screens/Home/GroupMenu/Menus/BanedUsersList.js
  src/screens/Home/GroupMenu/Menus/EditGroup.js
  src/screens/Home/GroupMenu/Menus/EditGroupMember.js
  src/screens/Home/GroupMenu/Menus/GroupMembersList.js
  src/screens/Home/GroupMenu/Menus/JoinGroupRequest.js
  src/screens/Home/GroupMenu/Menus/MyGroups.js
  src/screens/Home/GroupMenu/Menus/SearchGroup.js
  src/screens/Home/GroupMenu/Stylesheet.js
  src/screens/Home/Home.js
  src/screens/InitialGroupMenu/Menus/MyGroups.js
  src/screens/InitialGroupMenu/Menus/SearchGroup.js
  src/screens/InitialGroupMenu/Stylesheet.js
  src/screens/Loading/Loading.js
Labels: bug, enhancement
