Repository mapshare/mobile-app-frontend, pull requests merged in 2019-12, with the labels that each got.

#49 Add Chat Room Active Members, fix some bugs
  src/actions/groupActions.js
  src/actions/groupChatRoomAction.js
  src/actions/groupFeedAction.js
  src/actions/logInActions.js
  src/data/key.js
  src/navigation/Router/router.js
  src/reducers/groupChatRoomReducer.js
  src/reducers/groupReducer.js
  src/screens/Forms/CreatePost/CreatePost.js
  src/screens/Forms/EditPost/EditPost.js
  src/screens/Forms/Stylesheet.js
  src/screens/Groups/GroupChat/GroupChat.js
  src/screens/Groups/GroupChat/Stylesheet.js
  src/screens/Groups/GroupChat/activeMemberList.js
  src/screens/Groups/GroupChat/activeMemberMenuBtn.js
  src/screens/Groups/GroupFeed/GroupFeed.js
  src/screens/Home/Home.js
  src/screens/InitialGroupMenu/Menus/MyGroups.js
  src/screens/InitialGroupMenu/Stylesheet.js
  src/screens/Profile/Profile.js
Labels: bug, enhancement

#52 Detail Window Edit/Delete and Reviews
  src/actions/bottomWindowAction.js
  src/actions/groupMarkAction.js
  src/actions/modalWindowAction.js
  src/assests/images/pin-map-icon.jpg
  src/data/key.js
  src/navigation/Router/router.js
  src/reducers/bottomWindowReducer.js
  src/reducers/groupMarkReducer.js
  src/reducers/modalWindowReducer.js
  src/reducers/rootReducer.js
  src/screens/BottomWindow/BottomWindow.js
  src/screens/BottomWindow/Stylesheet.js
  src/screens/ConfirmDelete/ConfirmDelete.js
  src/screens/ConfirmDelete/Stylesheet.js
  src/screens/Forms/AddCustomMarkForm/AddCustomMarkForm.js
  src/screens/Forms/AddMark/AddMarkForm.js
  src/screens/Forms/CustomMarkOptionsForm/CustomMarkOptionsForm.js
  src/screens/Forms/EditGroupMark/EditGroupMark.js
  src/screens/Forms/EditGroupMark/Stylesheet.js
  src/screens/Forms/LocationReview/LocationReviewFrom.js
  src/screens/Forms/LocationReview/Stylesheet.js
  src/screens/Forms/RenderField/Stylesheet.js
  src/screens/Forms/validate/validation.js
  src/screens/LocationDetailWindow/LocationDetailWindow.js
  src/screens/LocationDetailWindow/Stylesheet.js
  src/screens/Map/Map.js
  src/screens/Marks/Marks.js
  src/screens/ModalWindow/ModalWindow.js
  src/screens/ModalWindow/Stylesheet.js
Labels: enhancement

#53 simple welcome landing
  src/screens/WelcomeLanding/Stylesheet.js
  src/screens/WelcomeLanding/WelcomeLanding.js
Labels: enhancement

#59 Wz wip2
  android/app/src/main/assets/index.android.bundle
  src/actions/groupEventAction.js
  src/data/key.js
  src/reducers/groupEventReducer.js
  src/screens/Events/Event.js
  src/screens/Events/Stylesheet.js
  src/screens/Map/Map.js
  src/screens/ModalWindow/ModalWindow.js
  src/screens/ModalWindow/Stylesheet.js
  src/screens/Profile/Profile.js
Labels: enhancement

#62 fix minor bugs
  src/actions/modalWindowAction.js
  src/data/key.js
  src/reducers/modalWindowReducer.js
  src/screens/ConfirmDelete/ConfirmDelete.js
  src/screens/Forms/EditGroupMark/EditGroupMark.js
  src/screens/Forms/LocationReview/LocationReviewFrom.js
  src/screens/LocationDetailWindow/LocationDetailWindow.js
  src/screens/LocationDetailWindow/Stylesheet.js
  src/screens/ModalWindow/ModalWindow.js
  src/screens/ModalWindow/Stylesheet.js
Labels: bug

#61 Wz wip2
  src/actions/userActions.js
  src/reducers/userReducer.js
  src/screens/AddMark/AddMark.js
  src/screens/Events/Event.js
  src/screens/Events/Stylesheet.js
  src/screens/Forms/AddMark/AddMarkForm.js
  src/screens/Forms/Login/LoginForm.js
  src/screens/Forms/SignUp/SignUpForm.js
  src/screens/Forms/validate/validation.js
  src/screens/Map/Map.js
  src/screens/Marks/Marks.js
  src/screens/ModalWindow/ModalWindow.js
  src/screens/Profile/Profile.js
Labels: bug

#63 Fix buttons bug
  src/actions/groupMarkAction.js
  src/actions/modalWindowAction.js
  src/data/key.js
  src/reducers/modalWindowReducer.js
  src/screens/ConfirmDelete/ConfirmDelete.js
  src/screens/Forms/EditGroupMark/EditGroupMark.js
  src/screens/Forms/LocationReview/LocationReviewFrom.js
  src/screens/LocationDetailWindow/LocationDetailWindow.js
Labels: bug

#65 Minor Bug Fixes and Welcome Page Add
  App.js
  android/app/src/main/assets/index.android.bundle
  src/navigation/Router/router.js
  src/screens/AddMark/AddMark.js
  src/screens/Forms/AddMark/AddMarkForm.js
  src/screens/Login/Login.js
  src/screens/Login/Stylesheet.js
  src/screens/SignUp/SignUp.js
  src/screens/WelcomeLanding/Stylesheet.js
  src/screens/WelcomeLanding/WelcomeLanding.js
Labels: bug

#66 Custom category display
  src/screens/CategoryOptions/CategoryOptions.js
  src/screens/LocationDetailWindow/LocationDetailWindow.js
Labels: bug
